package com.aaa.web.page;

import org.openqa.selenium.By;

public class DIHomePage {

    public static By btnContinueOnQueueSelection;
    public static By btnSearchCalls;
    public static By lnkSearchCalls;
    public static By lnkLogout;
    public static By btnLogout;
    public static By labelPhoneTypeOnDIMCD;
    public static By btnMCDwindowClose;
    public static By txtSearchCallID;
    public static By SearchButton;
    public static By clickOnCallIdLinkInDI;
    public static By linkProfile1InProfileMenu;
    public static By tabDiProfile;
    public static By callIdInProfileMenu;
    public static By callIdInProfileDivs;
    public static By tabTruckLoad;
    public static By truckLoadDefaultView;
    public static By phoneTypeOnDefaultView;
    public static By closeFacilityWindow;
    public static By emptyResultsForCallID;
    public static By phoneTypeOnDefaultViewTruckLoad;
    public static By profile1SPPDI;
    public static By iconCloseOnQueueSelection;
    public static By btnCancelOnQueueSelection;
    public static By txtStartDate;
    public static By lblMCDPTATimeZone;
    public static By btnDispatchTab;
    public static By lblQueueFieldFirstItem;
    public static By lblQueueFieldSecondItem;
    public static By btnAddOnQueueWindow;
    public static By btnRemoveOnQueueWindow;
    public static By txtQueueFilterDispatch;
    public static By txtQueueFilterSelected;
    public static By lnkSelectAll;
    public static By lblHighlightedFieldValue;
    public static By lblQueueFieldFirstItemInSelected;
    public static By txtqueueFilterSpot;
    public static By btnCloseOnQueueWindow;
    public static By lnkUserProfile;
    public static By lnkApplicationMenu;
    public static By btnChangeEditQueueSelection;
    public static By lnkFasdfProfileOnProfilesMenu;
    public static By lnkParamProfileOnProfilesMenu;
    public static By drpdwnHiddenTabs;
    public static By listOfHiddenTabs;
    public static By linkTabPlusButton;
    public static By listOfHiddenTabsInPlusButton;
    public static By linkMinimizeProfileWindow;
    public static By statusInBeyondETATabOnProfileWindow;
    public static By linkProfileWindowPoppedOut;
    public static By linkSettingsGearIconOnProfileWindow;
    public static By btnIDOnProfileWindow;
    public static By btnDateOnProfileWindow;
    public static By btnIDArrowOfProfileWindow;
    public static By btnDateArrowOfProfileWindow;
    public static By lblPriorityOfIDOnProfileWindow;
    public static By lblOrderOfIDOnProfileWindow;
    public static By btnSaveOfIDOnProfileWindow;
    public static By drpdwnOrder;
    public static By drpdwnPriority;
    public static By txtIDvalue;
    public static By txtDateValue;
    public static By iconSortAscensing;
    public static By iconSortDescending;
    public static By lnkQAAutoOneProfileOnProfilesMenu;
    public static By lnkQAAutoTwoProfileOnProfilesMenu;
    public static By lnkRemoveAll;
    public static By areaSelectedResultsGrid;
    public static By lnkChangeSetQueueSelection;
    public static By btnSpotTab;
    public static By lblQueueFirstItemInSpotContainer;
    public static By lblSelectedQueueFirstItemInSpotContainer;
    public static By lblHighlightedFieldValueSpot;
    public static By lnkSelectAllSpot;
    public static By lstSelectedQueueFields;
    public static By dispatchQueuePopup;
    public static By drpdwnIDOrder;
    public static By drpdwnIDPriority;
    public static By drpdwnDescendindOrder;
    public static By tabActionRequired;
    public static By tabActionRequiredColumnId;
    public static By iconSortAscensingInProfileWindow;
    public static By iconSortDescendingInProfileWindow;
    public static By btnSaveSettingsInProfileWindow;
    public static By btnSaveOfIDAndDateOnProfileWindow;
    public static By btnCloseOnUserProfile;
    public static By tabAllCalls;
    public static By txtSearchMemberNumber;
    public static By lnkRedFlagInHiddenTabOne;
    public static By statusInRedFlagTabOnProfileWindow;
    public static By dispatch;
    public static By selectAll;
    public static By add;
    public static By btnContinue;
    public static By idInRedFlagTabInProfileWindow;
    public static By  lnkRedFlagUnderHiddenTab;
    public static By  lnkRedFlagUnderAddMenuIcon;
    public static By tabNextToAllCallsTab;
    public static By lnkBeyondETAUnderHiddenTab;
    public static By lnkBeyodETAUnderAddMenuIcon;
    public static By txtNoRecordsFoundOnETAtab;
    public static By paramWindow;
    public static By lnkcloseProfileWindow;
    public static By iconCloseOnFacilityPTA;
    public static By lnkFirstCallIdInDI;
    public static By lnkCallIdInMessagePopup;
    public static By txtFacilityIDOnTruckLoad;
    public static By lnkFacilityIDOnTruckLoad;
    public static By callIDOnTruckLoadDivs;
    public static By callIdInTruckLoadMenu;
    public static By lblETStatusOnMessagePopup;
    public static By lnkCallIdOnMessagePopup;
    public static By lnkMessagePopup;
    public static By chkBoxMessagesInMessagepopup;
    public static By btnAcknowledgeOnMesssagepopup;
    public static By lblCallIDInProfileResultsWindow;
    public static By lblCallIDResultsInTruckLoadWindow;
    public static By lblDateHeaderInTruckLoad;
    public static By iconDesendingOrderForDate;
    public static By callIDInProfileTab;
    public static By callIDInTruckLoadTab;
    public static By lnkCloseSpotFacilityOnTruckLoad;
    public static By lnkCloseIconOnTruckLoad;
    public static By txtOpenNewProfile;
    public static By dialogSetProfileName;
    public static By btnSaveAndContinueInSetProfileNameWindow;
    public static By txtBoxHighligetedInRedInSetProfileNameWindow;
    public static By lblUserProfileNameEmptyInSetProfileNameWindow;
    public static By txtNameInSetProfileNameWindow;
    public static By lblIDSelectedSection;
    public static By lblStsSelectedSts;
    public static By selectCallsType;
    public static By lblOkeyAfterLogout;
    public static By profileInProfileList;
    public static By labelActionReqTab;
    public static By callIDOnActionReqTab;
    public static By callIdStatusOnActionReqTab;
    public static By lblDispathTitle;
    public static By txtStartDateOnSearchCallWindow;
    public static By txtEndDateInSearchCallWindow;
    public static By lnkResetSetting;
    public static By lnkIDOnProfileWindow;
    public static By lnkDateOnProfileWindow;
    public static By lnkStsOnProfileWindow;
    public static By lnkRemoveAllProfileWindow;
    public static By lnkZoneProfileWindow;
    public static By lnkDateInUnselectedProfileWindow;
    public static By txtFilterInProfileWindow;
    public static By lnkIDInUnselectedProfileWindow;
    public static By btnAddInProfileWindow;
    public static By lnkMessagesTabOnMessagePopUp;
    public static By lnkNewMessageTabOnMessagePopUp;
    public static By addressBookTabOnMessagePopUp;
    public static By listOfUsersOnAddressBookOnMessagepopup;
    public static By callTakerUserOnMessagePopUp;
    public static By dispatchUserOnMessagePopUp;
    public static By btnAddRecipientOnMessagePopUp;
    public static By btnSendMessage;
    public static By lblMessageTextBoxError;
    public static By txtMessageTextBox;
    public static By lblCharactersRemaining;
    public static By lblMessageOnMessagePopUp;
    public static By recipientGroupOnMessagePopUp;
    public static By chkboxFirstMessageInMessagePopUp;
    public static By rdbtnGroupOnMessagePopUp;
    public static By btnReplyOnMessagePopUp;
    public static By lnkPopoutForMessagePopUp;
    public static By rdbtnUserButtonHighlighted;
    public static By lblRecipientOnNewmessageTab;
    //
    public static By iconPlusOnGroupsOnMessagepopup;
    public static By lnkRemoveRecipient;
    public static By lblNoMessageFound;
    public static By deleteSelectedQueues;
    public static By noFaforiteCalls;
    public static By btnQueueInFavorites;
    public static By lblQueueSelection;
    public static By txtStatusInSearchCalls;
    public static By lblSPPDisplatch;
    public static By nofavoriteCalls;
    public static By favoriteList;
    public static By emptyFavoriteCall;
    public static By linkClickOnFavorites;
    public static By closeIconOnFacilitySelectedOnTruckload;
    public static By lnkRedFlagUnderProfileTab;
    public static By truckLoadDefaultViewinSPP;




    static {
        lnkRemoveAll=By.id("queue-list-removeall-selected");
        iconCloseOnQueueSelection=By.cssSelector("span[id='ui-dialog-title-queue-select-dialog']+a");
        btnCancelOnQueueSelection=By.id("queue-select-button-cancel");
        btnContinueOnQueueSelection = By.id("queue-select-button-continue");
        btnSearchCalls = By.xpath("//*[@id='search-calls-lnk']/a/i");
        lnkSearchCalls = By.id("search-calls-lnk");
        lnkLogout = By.id("d3ui-unified-header-logOut");
        btnLogout = By.id("confirmation-yes-btn");
        labelPhoneTypeOnDIMCD=By.xpath("//div[@class='calldetails-mbr-contact-item primary']/div/label");
        btnMCDwindowClose=By.xpath("//*[@id='mcd-panel-btns']//following::i[contains(@class,'icon-remove-sign')]");
        txtSearchCallID=By.id("call-search-call-id");
        SearchButton=By.xpath("//*[@id='call-search-search-button']/span[2]");
        clickOnCallIdLinkInDI = By.cssSelector("table[id='call-search-results-table'] tbody tr[id*='call-'] a");
        linkProfile1InProfileMenu=By.xpath("//ul[@id='profile-dropdown-menu']//*[contains(text(),'param')]");
        tabDiProfile=By.id("topbar-profiles-menu-btn");
        callIdInProfileMenu=By.id("profile_callid");
        callIdInProfileDivs = By.cssSelector("div[id='profile-tab-data-display'] div[class*='d3ui-datagrid-row profile-data-call-row profile-child-row']");
        tabTruckLoad=By.id("topbar-truckload-menu-btn");
        //truckLoadDefaultView=By.xpath("//ul[@id='truckload-dropdown-menu']/li[3]/a/span[2]");
        truckLoadDefaultView=By.xpath("//*[@id='truckload-dropdown-menu']//*[contains(text(),'Default View')]");
        phoneTypeOnDefaultView = By.xpath("//*[@id='facility-list-data-panel']/li[2]/span[3]");
        closeFacilityWindow = By.xpath("//*[@id='pta-close']/span");
        emptyResultsForCallID = By.cssSelector("div table[id='call-search-results-table'] tr[class='odd lastsearchrecord'] td[class='dataTables_empty']");
        phoneTypeOnDefaultViewTruckLoad =By.xpath("//*[@id='facility-list-data-panel']/li[1]/span[3]");
        profile1SPPDI=By.id("//*[@id='profile-dropdown-menu']/li[6]/a");
        txtStartDate = By.id("call-search-start-date");
        lblMCDPTATimeZone =By.cssSelector("span[data-field='pta']+span span");
        btnDispatchTab =By.id("queue-select-dispatch-tab");
        lblQueueFieldFirstItem = By.xpath("//ul[@id='queue-list-fields-dispatch']/li[1]/a/span/span[1]");
        lblQueueFieldFirstItemInSelected = By.xpath("//ul[@id='queue-list-fields-selected']/li[1]/a/span/span[1]");
        lblQueueFieldSecondItem = By.xpath("//ul[@id='queue-list-fields-dispatch']/li[2]/a/span/span[1]");
        btnAddOnQueueWindow = By.id("queue-select-add-button");
        btnRemoveOnQueueWindow = By.id("queue-select-remove-button");
        txtQueueFilterDispatch = By.id("queue-filter-dispatch");
        txtQueueFilterSelected = By.id("queue-filter-selected");
        lnkSelectAll = By.id("queue-list-selectall-dispatch");
        lblHighlightedFieldValue = By.xpath("//*[@id=\"queue-list-fields-dispatch\"]/li/a[contains(@class,'ui-state-highlight')]");
        txtqueueFilterSpot = By.id("queue-filter-spot");
        btnCloseOnQueueWindow = By.id("queue-select-button-cancel");
        lnkUserProfile = By.id("user-profile-menu-item");
        lnkApplicationMenu = By.xpath("//ul[1]/li[5]/a[contains(text(),'Application ')]");
        btnChangeEditQueueSelection = By.cssSelector("div[id*='user-profile-queues-table-']+span");
        lnkFasdfProfileOnProfilesMenu = By.xpath("//ul[@id='profile-dropdown-menu']/li[6]/a");
        lnkParamProfileOnProfilesMenu = By.xpath("//ul[@id='profile-dropdown-menu']/li[7]/a");
        lnkQAAutoOneProfileOnProfilesMenu = By.xpath("//ul[@id='profile-dropdown-menu']/li[9]/a");
        lnkQAAutoTwoProfileOnProfilesMenu = By.xpath("//ul[@id='profile-dropdown-menu']/li[10]/a");
        drpdwnHiddenTabs=By.className("view-hidden-profile-tabs-btn");
        listOfHiddenTabs=By.xpath("//li[@class='d3ui-menu-item d3ui-menu-item-counter']/a/span[2]");
        linkTabPlusButton=By.className("add-profile-tab-btn");
        listOfHiddenTabsInPlusButton=By.xpath("//ul[@class='add-tab-list d3ui-menu d3ui-menu-constrained']/li/a/span[2]");
        linkMinimizeProfileWindow=By.xpath("//div[@class='d3ui-panel-menu profile-menu']/a[4]");
        statusInBeyondETATabOnProfileWindow=By.className(".profile-call-status-descr");
        linkProfileWindowPoppedOut=By.xpath("//div[@class='d3ui-panel-menu profile-menu']/a[3]");
        linkSettingsGearIconOnProfileWindow=By.xpath("//a[@title='Customize the profile']");
        drpdwnPriority=By.xpath("//span[@class='priority-title']/../select");
        drpdwnOrder=By.xpath("//span[@class='order-title']/../select");
        iconSortAscensing = By.xpath("//div[@id='profile_callid']//i[@class='icon-sort-up']");
        iconSortDescending = By.xpath("//div[@id='profile_calldate']//i[@class='icon-sort-down']");
        areaSelectedResultsGrid =By.id("queue-list-fields-selected");
        lnkChangeSetQueueSelection=By.cssSelector("div[id='window-pane-taskbar']+header a+ul li[id='calladjustments-link']+li span");
        btnSpotTab=By.id("queue-select-spot-tab");
        lblQueueFirstItemInSpotContainer = By.xpath("//ul[@id='queue-list-fields-spot']/li[1]/a/span/span[1]");
        lblSelectedQueueFirstItemInSpotContainer = By.xpath("//ul[@id='queue-list-fields-selected']/li[1]/a/span/span[1]");
        lblHighlightedFieldValueSpot = By.xpath("//*[@id=\"queue-list-fields-spot\"]/li/a[contains(@class,'ui-state-highlight')]");
        lnkSelectAllSpot = By.id("queue-list-selectall-spot");
        lstSelectedQueueFields=By.cssSelector("ul[id='queue-list-fields-selected'] li");
        dispatchQueuePopup=By.id("ui-dialog-title-queue-select-dialog");
        tabActionRequired = By.xpath("//a[@class='profile_1']");
        tabActionRequiredColumnId = By.xpath("//div[@id='profile_callid']");
        iconSortAscensingInProfileWindow = By.xpath("//div[@id='profile_callid']//i[@class='icon-sort-up']");
        iconSortDescendingInProfileWindow = By.xpath("//div[@id='profile_callid']//i[@class='icon-sort-down']");
        btnSaveSettingsInProfileWindow = By.xpath("//button[@title='Save profile settings']");
        btnSaveOfIDAndDateOnProfileWindow=By.xpath("//div[72]/div[3]/div/button[2]");
        btnCloseOnUserProfile = By.cssSelector("div[id*='user-profile-dialog-']+div div");
        tabAllCalls=By.className("profile_3");
        btnIDOnProfileWindow=By.cssSelector("ul[class='selected selectable-list ui-sortable'] li:nth-child(1) a");
        btnDateOnProfileWindow=By.cssSelector("ul[class='selected selectable-list ui-sortable'] li:nth-child(2) a");
        btnIDArrowOfProfileWindow=By.cssSelector("ul[class='selected selectable-list ui-sortable'] li:nth-child(1) button");
        btnDateArrowOfProfileWindow=By.cssSelector("ul[class='selected selectable-list ui-sortable'] li:nth-child(2) button");
        lblPriorityOfIDOnProfileWindow=By.xpath("//div[@class='priority']/span");
        lblOrderOfIDOnProfileWindow=By.xpath("//div[@class='order']/span");
        txtIDvalue=By.cssSelector("ul[class='selected selectable-list ui-sortable'] li:nth-child(1) a span+span span");
        txtDateValue=By.cssSelector("ul[class='selected selectable-list ui-sortable'] li:nth-child(2) a span+span span");
        statusInRedFlagTabOnProfileWindow=By.xpath(" //*[@id='up_964_profile_3-20171230-20000']/div[2]");
        txtSearchMemberNumber=By.id("call-search-member-number");
        lnkRedFlagInHiddenTabOne = By.xpath("//*[@class='hidden-tab-list d3ui-menu d3ui-menu-constrained']//*[text()='Red-Flag Calls']");
        dispatch=By.xpath("//*[@id='queue-select-dispatch-tab']");
        selectAll=By.id("queue-list-selectall-dispatch");
        add=By.xpath("//*[@id='queue-select-add-button']/span");
        btnContinue=By.xpath("//*[@id='queue-select-button-continue']/span");
        idInRedFlagTabInProfileWindow=By.xpath("//div[@id='profile-tab-data-display']/div/div/div[4]");
        lnkRedFlagUnderHiddenTab= By.xpath("//*[@class='hidden-tab-list d3ui-menu d3ui-menu-constrained']//*[text()='Red-Flag Calls']");
        lnkRedFlagUnderAddMenuIcon=By.xpath("//*[@class='add-tab-list d3ui-menu d3ui-menu-constrained']//*[text()='Red-Flag Calls']");
        tabNextToAllCallsTab=By.cssSelector("div[class='profile-tabs-container ui-tabs ui-widget ui-widget-content ui-corner-all'] ul li:nth-child(2) span+a");
        lnkBeyondETAUnderHiddenTab = By.xpath("//*[@class='hidden-tab-list d3ui-menu d3ui-menu-constrained']//*[text()='Beyond ETA']");
        lnkBeyodETAUnderAddMenuIcon=By.xpath("//*[@class='add-tab-list d3ui-menu d3ui-menu-constrained']//*[text()='Beyond ETA']");
        txtNoRecordsFoundOnETAtab=By.className("no-calls-profile-message");
        paramWindow=By.className("profile-tab-list d3ui-panel-tabs-nav ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all ui-sortable");
        lnkcloseProfileWindow=By.xpath("//div[@class='d3ui-panel-menu profile-menu']/a[5]");
        iconCloseOnFacilityPTA=By.cssSelector("span[id='ui-dialog-title-pta-dialog']+a");
        lnkFirstCallIdInDI=By.xpath("//table[@id='call-search-results-table']/tbody/tr[1]/td[2]/a");
        lnkCallIdInMessagePopup=By.xpath("//*[@id=\"messages-grid\"]/tbody/tr[2]/td[6]/a");
        txtFacilityIDOnTruckLoad = By.xpath("//*[@id='facility-header-tag-it']/div/div/ul/li/input");
        lnkFacilityIDOnTruckLoad = By.cssSelector("ul[class='ui-autocomplete ui-menu ui-widget ui-widget-content ui-corner-all'] li a");
        callIDOnTruckLoadDivs = By.cssSelector("div[id='truckload-calls-grid-data'] div[class*='d3ui-datagrid-row tl-child-row tl-data-call-row']");
        callIdInTruckLoadMenu = By.xpath("//*[@id='tl-calls-4']");
        lblETStatusOnMessagePopup = By.xpath("//td[@title='ETA Requested']");
        lnkMessagePopup=By.id("call-messages-btn");
        chkBoxMessagesInMessagepopup=By.id("cb_messages-grid");
        btnAcknowledgeOnMesssagepopup=By.id("msg-ack-btn");
        lblCallIDInProfileResultsWindow=By.cssSelector("div[id='profile-tab-data-display'] div[class*='d3ui-datagrid-row profile-data-call-row profile-child-row'] div+div[class='d3ui-datagrid-call-cell profile-call-width-cell-callid']");
        lblCallIDResultsInTruckLoadWindow=By.cssSelector("div[id='truckload-calls-grid-data'] div[class*='d3ui-datagrid-row tl-child-row tl-data-call-row'] div+div[class='d3ui-datagrid-call-cell tl-call-width-cell-callid']");
        lblDateHeaderInTruckLoad=By.id("tl-calls-3");
        iconDesendingOrderForDate=By.className("icon-sort-down");
        lnkCloseSpotFacilityOnTruckLoad=By.xpath("//*[@id='facility-header-tag-it']/div/div/ul/li[1]/a/span[2]");
        lnkCloseIconOnTruckLoad=By.xpath("//*[@id='truckload-panel']/div[2]/div[1]/div[1]/div/a[4]/i");
        txtOpenNewProfile = By.id("open-new-profile-btn");
        dialogSetProfileName = By.xpath("//div[@aria-labelledby = 'ui-dialog-title-new-user-profile-dlg']");
        btnSaveAndContinueInSetProfileNameWindow = By.id("new-user-profile-dlg-open");
        txtBoxHighligetedInRedInSetProfileNameWindow = By.xpath("//input[@class='text ui-state-error ui-state-error-text']");
        lblUserProfileNameEmptyInSetProfileNameWindow = By.id("new-user-profile-dlg-error");
        txtNameInSetProfileNameWindow = By.id("new-user-profile-dlg-name");
        lblIDSelectedSection = By.xpath("//div[@class='d3ui-panelsettings-container']//ul[@class='selected selectable-list ui-sortable']//span[contains(text(),'ID')]");
        lblStsSelectedSts = By.xpath("//div[@class='d3ui-panelsettings-container']//ul[@class='selected selectable-list ui-sortable']//span[text()='Sts']");
        selectCallsType=By.xpath("//input[@id='call-search-calls-type-select']");
        lblOkeyAfterLogout=By.xpath("scripts-immediate-dialog-okayBtn");
        labelActionReqTab=By.xpath("//*[contains(text(), 'Action Required')]");
        lblDispathTitle=By.xpath(" //div[@class='d3ui-app-switch-selected d3ui-logo-dispatch'][contains(@title,'D3 Dispatch')]");
        txtStartDateOnSearchCallWindow=By.xpath("//input[@id='call-search-start-date']");
        txtEndDateInSearchCallWindow = By.xpath("//*[@id='call-search-end-date']");
        lnkResetSetting=By.xpath("//*[@id='profile-1043-tab-settings']//a[contains(text(),'Reset')]");
        lnkIDOnProfileWindow=By.xpath("//*[@id='profile-1043-tab-3-selected']//span[contains(text(),'ID')]");
        lnkDateOnProfileWindow=By.xpath("//*[@id='profile-1043-tab-3-selected']//span[contains(text(),'Date')]");
        lnkStsOnProfileWindow=By.xpath("//*[@id='profile-1043-tab-3-selected']//span[contains(text(),'Sts')]");
        lnkRemoveAllProfileWindow=By.xpath("//*[@id='profile-1043-tab-settings']//a[contains(text(),'Remove All')]");
        lnkZoneProfileWindow=By.xpath("//*[@id='profile-1043-tab-3-unselected']//span[contains(text(),'Zone')]");
        lnkDateInUnselectedProfileWindow=By.xpath("//*[@id='profile-1043-tab-3-unselected']//span[contains(text(),'Date')]");
        txtFilterInProfileWindow=By.xpath("//*[@id='profile-1043-tab-3-avail-col']");
        lnkIDInUnselectedProfileWindow=By.xpath("//*[@id='profile-1043-tab-3-unselected']//span[contains(text(),'ID')]");
        btnAddInProfileWindow=By.xpath("//*[@id='profile-1043-tab-settings']//span[contains(text(),'Add')]");
        lnkMessagesTabOnMessagePopUp = By.id("message-link");
        lnkNewMessageTabOnMessagePopUp=By.id("send-message-link-title");
        addressBookTabOnMessagePopUp=By.id("address-book-title-tab");
        listOfUsersOnAddressBookOnMessagepopup=By.xpath("//div[@id='send-message-to-data-table']/div[3]/div/div");
        callTakerUserOnMessagePopUp=By.xpath("//*[contains(text(), 'AUTOCR1 - CALLTAKER AUTOMATION')]/..");
        dispatchUserOnMessagePopUp=By.xpath("//*[contains(text(), 'AUTODI1 - DISPATCHERUSER AUTOMATION')]/..");
        btnAddRecipientOnMessagePopUp=By.id("add-recipient-btn");
        btnSendMessage=By.id("send-message-btn");
        lblMessageTextBoxError=By.className("formErrorContent");
        txtMessageTextBox=By.id("send-message-msg");
        lblCharactersRemaining=By.id("send-message-remaining-text");
        lblMessageOnMessagePopUp=By.xpath("//*[@id='messages-grid']/tbody/tr[2]/td[6]");
        recipientGroupOnMessagePopUp=By.xpath("//*[contains(text(), 'ARI - ARISE CR')]/..");
        chkboxFirstMessageInMessagePopUp=By.xpath("//*[@id='messages-grid']/tbody/tr[2]/td[1]/input");
        rdbtnGroupOnMessagePopUp=By.xpath("//label[@for='snd-msg-group']");
        btnReplyOnMessagePopUp=By.id("msg-reply-btn");
        lnkPopoutForMessagePopUp=By.xpath("//*[@id='messages-panel']/div[1]/div[1]/div/a[1]");
        rdbtnUserButtonHighlighted=By.xpath("//label[@for='snd-msg-user'][@aria-pressed='true']");
        lblRecipientOnNewmessageTab=By.xpath("//div[@id='send-message-to-container']//span[@class='tagit-label']");
//
        iconPlusOnGroupsOnMessagepopup=By.xpath("//div[@class='d3ui-cell address-book-icon']/span/..");
        lnkRemoveRecipient=By.xpath("//*[@id='send-message-to-container']/ul/li[1]/a");
        lblNoMessageFound=By.xpath("//div[@dir='ltr'][contains(text(), 'No records to view')]");
        deleteSelectedQueues=By.xpath("//*[@id='queue-list-fields-selected']//span[contains(text(),'Everything (144)')]");
        btnQueueInFavorites=By.xpath("//ul[@id='queue-list-fields-favorites']//span[contains(text(),'Everything (144)')]");
        noFaforiteCalls=By.xpath("//div[@id='profile-tab-data-display']//div[contains(text(),'No records found')]");
        lblQueueSelection=By.id(" ui-dialog-title-queue-select-dialog");
        lblSPPDisplatch = By.xpath("//div[@class='d3ui-app-switch-selected d3ui-logo-spp']");
        nofavoriteCalls=By.id("//div[@id='profile-tab-data-display']//div[contains(text(),'No records found')]"); //*[@id="up_33_profile_33-20180213-20003"]/div[2]/div[3]
        emptyFavoriteCall=By.id("profile-tab-data-display");
        linkClickOnFavorites=By.id("queue-select-favorites-tab");
        closeIconOnFacilitySelectedOnTruckload=By.xpath("//span[@class='ui-icon ui-icon-close']");
        lnkRedFlagUnderProfileTab=By.xpath("//*[@id='profile-window-1043']//*[contains(text(),'Red-Flag')]");
        truckLoadDefaultViewinSPP = By.xpath("//*[@id='truckload-dropdown-menu']//*[contains(text(),'Truckload - DEFAULT')]");
    }
    public static By linkCallIDOnMessagePopUp(String callId){
        String xpath = "//*[@id=\"messages-grid\"]/tbody/tr//a[contains(text(),'"+callId+"')]";
        lnkCallIdOnMessagePopup=By.xpath(xpath);
        return lnkCallIdOnMessagePopup;
    }
    public static By callIDInProfileTab(String callId){
        String xpath = "//*[contains(@id,'profile_3-"+callId+"')]"; //*[contains(@id,'profile_3-20180124-20063')]
        callIDInProfileTab=By.xpath(xpath);
        return callIDInProfileTab;
    }

    public static By callIDInTruckLoadTab(String callId){
        String xpath = "//*[contains(@id,'tl-callrow-"+callId+"')]"; //*[contains(@id,'profile_3-20180124-20063')]
        callIDInTruckLoadTab=By.xpath(xpath);
        return callIDInTruckLoadTab;
    }
    public static By profileNameInProfileList(String profile){
        profileInProfileList = By.xpath("//*[@id='profile-dropdown-menu']/li/a//*[contains(text(),'"+profile+"')]");

        return profileInProfileList;
    }

    public static By callIDInActionrequiredProfileTab(String callId, String callIdDate){

        callIDOnActionReqTab=By.xpath("//*[contains(@id,'profile_1-"+callIdDate+"-"+callId+"')]");
        return callIDOnActionReqTab;
    }
    public static By getcallIDStatusInActionrequiredProfileTab(String callId, String callIdDate){

        callIdStatusOnActionReqTab=By.xpath("//*[contains(@id,'profile_1-"+callIdDate+"-"+callId+"')]/div[2]/div[2]");
        return callIdStatusOnActionReqTab;
    }

    public static By favoriteCallsList(String callIdAndDate){
        String xpath = "//*[contains(@id,'profile_33-"+callIdAndDate+"')]//div[contains(@class,'call-status-icons-content')]";
        favoriteList=By.xpath(xpath);
        return favoriteList;
    }
}
