package com.aaa.web.page;

import org.openqa.selenium.By;

public class DIMCDPage {

    public static By btnAsignCallinMCD;
    public static By selectFacility;
    public static By selectFacilityZ;
    public static By selectFacilityB;
    public static By btnDispatchUpdateinMCD;
    public static By btnEnrouteUpdateinMCD;
    public static By selEnrouteTimeinMCD;
    public static By btnOnLocationUpdateinMCD;
    public static By btnClearCallUpdateinMCD;
    public static By selectPacesetterCodeJumpStart;
    public static By continueButton;
    public static By batteryTestedYes;
    public static By batteryFailedTestNo;
    public static By odometerReading;
    public static By enterComments;
    public static By submitButton;
    public static By lblPaceSetterCodeInMCD;
    public static By btnWindowCloseInMCD;
    public static By tabServiceInMCD;
    public static By btnCloseCall;
    public static By selPaceSetterResolutionCode;
    public static By lblCallClearedStatus;
    public static By txtReason;
    public static By lnkSelectFacility;
    public static By txtStatusOnStatusUpdate;
    public static By txtReasonOnStatusUpdate;
    public static By btnUpdateOnStatusUpdate;
    public static By btnETAinMCD;
    public static By selETATime;
    public static By linkMinimizeMCDwindow;
    public static By tabStatusUpdateInMCD;
    public static By txtStatusOfStatusUpdateInMCD;
    public static By txtReasonOfStatusUpdateInMCD;
    public static By btnUpdateOfStatusUpdateTabInMCD;
    public static By selectFacilityOnAssignTabInMCD;
    public static By cancelinMCDClearCall;
    public static By cancelCallServiceNotEnroute;
    public static By selectSecondFacilityOnAssignTabInMCD;
    public static By selectSecondFacilityOnDispatchTabInMCD;
    public static By setTimeForETA;
    public static By lblMemberFirstNameOnSummaryTabinMCD;
    public static By lblMemberLastNameOnSummaryTabinMCD;
    public static By lblMemberAddressOnSummaryTabinMCD;
    public static By lblMemberCityOnSummaryTabinMCD;
    public static By lblMemberStateOnSummaryTabinMCD;
    public static By lblMemberZipOnSummaryTabinMCD;
    public static By lblBreakdownAddressLocationOnSummaryTabinMCD;
    public static By lblVehicleYearOnSummaryTabinMCD;
    public static By lblVehicleMakeOnSummaryTabinMCD;
    public static By lblVehicleModelOnSummaryTabinMCD;
    public static By lblVehicleColorOnSummaryTabinMCD;
    public static By lblPaceSetterCodeOnSummaryTabinMCD;
    public static By lblTroubleCodeOnSummaryTabinMCD;
    public static By lblFunctionCodeOnSummaryTabinMCD;
    public static By lblFacilityIdAndNameOnSummaryTabinMCD;
    public static By lblMemberNumberOnSummaryTabinMCD;
    public static By btnTruckLoadOnSummaryTabinMCD;
    public static By lnkMemberTabinMCD;
    public static By lblMemberNumberOnMemberTabinMCD;
    public static By lblMemberFirstNameOnMemberTabinMCD;
    public static By lblMemberLastNameOnMemberTabinMCD;
    public static By lblMemberAddressOnMemberTabinMCD;
    public static By lblMemberLevelOnMemberTabinMCD;
    public static By lblMemberStatusOnMemberTabinMCD;
    public static By lblMemberExpirationDateOnMemberTabinMCD;
    public static By lblMemberCallsUsedOnMemberTabinMCD;
    public static By lblMemberCallsAllowedOnMemberTabinMCD;
    public static By lblLongTowAllowedOnMemberTabinMCD;
    public static By lblMemberPhoneNumberOnMemberTabinMCD;
    public static By lnkServiceTabinMCD;
    public static By lblPaceSetterCodeOnServiceTabinMCD;
    public static By lblTroubleCodeOnServiceTabinMCD;
    public static By lblServiceTypeInfoOnServiceTabinMCD;
    public static By lblFacilityNameAndNumberOnServiceTabinMCD;
    public static By btnShowBatteryServiceHistory;
    public static By lnkLocationsTabinMCD;
    public static By lblBreakDownLocationOnLocationsTabinMCD;
    public static By lblTowDestinationOnLocationsTabinMCD;
    public static By lnkVehicleTabinMCD;
    public static By lblVehicleTypeOnVehicleTabinMCD;
    public static By lblVehicleYearOnVehicleTabinMCD;
    public static By lblVehicleMakeOnVehicleTabinMCD;
    public static By lblVehicleModelOnVehicleTabinMCD;
    public static By lblVehicleColorOnVehicleTabinMCD;
    public static By btnSPOnMCDWindow;
    public static By btnTWOnMCDWindow;
    public static By btnNOGOOnMCDWindow;
    public static By btnOtherLocationOnMCDWindow;
    public static By btnMemberHomeOnMCDWindow;
    public static By btnNoTowPerformedOnMCDWindow;
    public static By btnRepairFacilityOnMCDWindow;
    public static By btnNOServiceOnMCDWindow;
    public static By txtAddressOnMCDWindow;
    public static By iconSearchAddressOnMCDWindow;
    public static By lnkClickOnFirstLink;
    public static By btnOriginalTowDestinationOnMCDWindow;
    public static By txtCommentOnMCDWindow;
    public static By lblCallSpottedStatus;
    public static By lblCallAssignedStatus;
    public static By lblCallDispatchedStatus;
    public static By lblCallENRouteStatus;
    public static By lblCallOnLocationStatus;
    public static By lblCallTowStatus;
    public static By txtFacilityInStautusUpdateWindow;
    public static By dropDownFacilityInStautusUpdateWindow;
    public static By dropDownReasonInStautusUpdateWindow;
    public static By lblFunctionCodeOnServiceTabinMCD;
    public static By btnTruckLoadOnServiceTabinMCD;
    public static By lblLongTowUsedOnMemberTabinMCD;
    public static By lblDOBOnMemberTabinMCD;
    public static By lblFacilityNameAndNumberOnServiceTabinDIMCD;
    public static By lblLanguagePreferenceOnMemberTabinMCD;
    public static By lblETATimeOnMCDWindow;
    public static By lblCommentsInMCDWindow;
    public static By lblMemberTypeOnMemberTabinMCD;
    public static By selectproblemResolutionCode;
    public static By txtMessageNoDataAvailableForOtherLocationInMCDWindow;
    public static By linkEnterAddreddManuallyForOttherLocationInMCDWindow;
    public static By txtEnterLocationForOtherLocationInMCDWindow;
    public static By txtEnterCrossStreeet1ForOtherLocationInMCDWindow;
    public static By txtEnterCrossStreeet2ForOtherLocationInMCDWindow;
    public static By txtEnterCityForOtherLocationInMCDWindow;
    public static By lblBatteryQuestionnaireInMCDWindow;
    public static By drpdwnStatusOnStatusUpdateTabInMCDWindow;
    public static By drpdwnReasonOnStatusUpdateTabInMCDWindow;
    public static By txtTruckInStautusUpdateTab;
    public static By txtZoneInStautusUpdateTab;
    public static By txtTechInStautusUpdateTab;
    public static By txtETAInStautusUpdateTab;
    public static By txtDateInStautusUpdateTab;
    public static By txtTimeInStautusUpdateTab;
    public static By txtCommentsInStautusUpdateTab;
    public static By btnCancelOfStatusUpdateTabInMCD;
    public static By lblCallStatusOnMCDWindow;
    public static By noTruckErrorText;
    public static By btnOKForNoTruckError;
    public static By drpdwnReasonGrayedOnStatusUpdateTabInMCDWindow;
    public static By txtETAFieldAlert;
    public static By txtReasonGrayedout;
    public static By btnPaymentOnMCDWindow;
    public static By drpDwnServicesAndChargesInMCDWindow;
    public static By drpDwnServicesAndChargesValueOnMCDWindow;
    public static By btnSaveInServiceAndChargesInMCDWindow;
    public static By txtCostInServiceAndChargesInMCDWindow;
    public static By txtCashCollectedInServiceAndChargesInMCDWindow;
    public static By btnCloseInSericeAndChargesInMCDWindow;
    public static By errorMessageAtEnterReasonOnMCDWindow;
    public static By txtTroubleCodeDropdown;
    public static By txtPaceSetterCodeSummaryTab;
    public static By iconPaymentOnMCDWindow;
    public static By drpdwnServicesOnPaymentOfMCD;
    public static By txtCostAPD;
    public static By txtCashCollectedAPD;
    public static By btnAPDSave;
    public static By btnCloseAPD;
    public static By btnSubmitAPD;
    public static By lnkStatusHistory;
    public static By lblStatusOnStatusHistoryTab;
    public static By lblReasonOnStatusHistoryTab;
    public static By lblPlusIconForCommentsSectionOnStatusHistoryTab;
    public static By lnkPlusIconForCommentsOnStatusHistoryTab;
    public static By lnkMaximizeMCDWindow;
    public static By lnkMinimizeMCDWindow;
    public static By lblMemberLevelOnSummaryTab;
    public static By txtCallTaker;
    public static By phoneNumberONMCD;
    public static By dynamicstatusButton;
    public static By btnNextSelected;
    public static By btnHighlightedStatus;
    public static By editIconOnPencilIcon;
    public static By imgPencilIcon;
    public static By btnAdd;
    public static By txtAddComment;
    public static By btnSave;
    public static By commentedData;
    public static By lblClearingTab;
    public static By btnPtaClose;
    public static By drpDwnAddSecondServicesAndChargesInMCDWindow;
    public static By phNumber;
    public static By lblClearCallStatusOnMCDHistoryWindow;
    public static By lblReasonCodeOnMCDHisotryWindow;
    public static By iconCloseOnStatusHistoryTabInMCDWindow;
    public static By btnBidCallInMCD;
    public static By btnBridgeCallinMCD;
    public static By btnDeclainCallinMCD;
    public static By btnPopOutInMCD;
    public static By lblPaceSetterValueInMCD;
    public static By txtTestCodeBattery;
    public static By batteryFailedTestYes;
    public static By batteryChargeYes;
    public static By batteryWarrantyYes;
    public static By txtBatteryType;
    public static By txtBatteryPrice;
    public static By iconAddressverifiedOnOriginalTowDestinaton;
    public static By lblCallBDStatus;
    public static By btnBDUpdateinMCD;
    public static By lblCallCAStatus;
    public static By lblTruckIDOnMCDSummaryScreen;
    public static By btnAcknowledgeMCD;
    public static By btnDupeCallOnMCD;
    public static By txtDuplicateCallTab;
    public static By lblCurrentCallOption;
    public static By MCDWindow;
    public static By btnCalldetailsUpdateActionButtons;
    public static By lblMemberNeedsCallBack;
    public static By iconPhone;
    public static By lblCallIDOnDuplicateCallTab;
    public static By lblFacilityOnDuplicateCallTab;
    public static By lblTruckOnDuplicateCallTab;
    public static By lblPaceSetterOnDuplicateCallTab;
    public static By lblStatusOnDuplicateCallTab;
    public static By lblNewDulicateCallInformationOnDuplicateCallTab;
    public static By lblSpotToFacilityOnDuplicateCallTab;
    public static By lblPaceSetterCodeDrpDwnOnDuplicateCallTab;
    public static By lblReasonDrpDwnOnDuplicateCallTab;
    public static By lblCommentsDrpDwnOnDuplicateCallTab;
    public static By btnDuplicateCallOnDuplicateCallTab;
    public static By errMsgForMandatoryFieldsOnDuplicateCallTab;
    public static By btnErrorMsgOkOnDuplicateCallTab;
    public static By txtSpotFacility;
    public static By txtPaceSetterCode;
    public static By txtReasonOnDuplicateCallTab;
    public static By txtAreaForComments;
    public static By lnkEditAdditionalInfo;
    public static By txtSpecialEquipementInMCDServiceTab;
    public static By btnSpecialEquipementSaveButton;
    public static By txtReasonCodeInUpdateStatus;
    public static By txtCommentsInUpdateStatus;
    public static By btnUpdatebuttonOnUpdateStatusPopup;
    public static By btnOkayOnErrorMessage;
    public static By lblSpecialEquipmentInMCDServiceTab;
    public static By lblLatestCommentsInMCDWindow;
    public static By sortdateInHisotrywindow;
    public static By lblStatusInHistoryStatus;
    public static By btnDupeCallPopUpNameOnMCD;
    public static By lnkToSelectFacilityOnNewDuplicateCall;
    public static By lnkToSelectPacesetterCode;
    public static By lnkSelectReasonOnNewDuplicateCall;
    public static By lblCallIdOnMcdWindow;
    public static By lblFacilityOnFacilitySummary;
    public static By lnkToCloseTheOpendCallInMCD;
    public static By lblStarColor;
    public static By btnShowBatteryServiceHistoryForRAP;
    public static By btnShowDuplicateCallHistoryForRAP;
    public static By lblvehiclevinOnServiceTabOfMCD;
    public static By lblvehicleOdometerOnServiceTabOfMCD;
    public static By lblvehicleIsRAPCallOnServiceTabOfMCD;
    public static By lblvehicleRAPEDSCallNumberOnServiceTabOfMCD;
    public static By iconRAPCall;
    public static By btnEditOnMCD;
    public static By btnPrintCallOnMCD;
    public static By btnCrediCardOnMCD;
    public static By unDefinedError;
    public static By lblErrorMessageOnAlert;
    public static By lblBatteryResoultionCodeOnClearingCall;
    public static By lblDateAndCallIdInShowBatteryHistory;
    public static By lblResoultionCodeLableInShowBatteryHistory;
    public static By lblResoultionCodeValueInShowBatteryHistory;
    public static By lblTestCodeLabelInShowBatteryHistory;
    public static By lblTestCodeValueInShowBatteryHistory;
    public static By lblFacilityLabelInShowBatteryHistory;
    public static By lblFacilityValueInShowBatteryHistory;
    public static By lblVehicleLableInShowBatteryHistory;
    public static By lblVehicleValueInShowBatteryHisotry;
    public static By iconCloseBatteryInformationTab;
    public static By btnPrintInBatteryServiceHistory;
    public static By selectFacilityOnAssignTabForDataUpdate;

    public static By lnkEditInMemberSummaryInMCDWindow;
    public static By btnSaveForMemberSummaryInMCDWindow;


    public static By btnAddInMCDWindow;
    public static By lnkCannedCommentsDroupDown;
    public static By selectCannedComment;
    public static By btnSaveCannedComments;
    public static By txtcannedComment;
    public static By lblESTTimeInComments;
    public static By listCannedComments;
    public static By txtUpdateStatus;

    public static By lblTowDestinationOnLocationsForRAPTabinMCD;
    public static By lblMemberClubCodeOnMemberTabinMCD;
    public static By lblCallDateInMCD;
    public static By selectOptionsActionsUPButton;
    public static By lblAddCommentsScreen;
    public static By btnCancelOnAddComments;
    public static By commentCountValueOnCommentSection;

    public static By lnkEditTowDestinationInServicesTabInMCDWindow;
    public static By lnkEditBreakDownLocationInServicesTabInMCDWindow;
    public static By txtStreetNumberInServicesTabInMCDWindow;
    public static By txtStreetNameInServicesTabInMCDWindow;
    public static By txtCrossStreet1InServicesTabInMCDWindow;
    public static By txtCrossStreet2InServicesTabInMCDWindow;
    public static By txtCityInServicesTabInMCDWindow;
    public static By txtStateInServicesTabInMCDWindow;
    public static By txtZipInServicesTabInMCDWindow;
    public static By txtLandMarkInServicesTabInMCDWindow;
    public static By txtLatitudeInServicesTabInMCDWindow;
    public static By txtLongitudeInServicesTabInMCDWindow;
    public static By lblAddressVerifiedInServicesTabInMCDWindow;
    public static By txtUpdateReasonInServicesTabInMCDWindow;
    public static By btnSaveButtonInServicesTabInMCDWindow;
    public static By btnCancelButtonInServicesTabInMCDWindow;
    public static By iconBreakDownLocationsCloseInMCDWindow;
    public static By txtAddressSearchInServicesInMCDWindow;
    public static By btnSearchButtonInServicesInMCDWindow;
    public static By lnkManualAddressEntryInTowDestinationInMCDWindow;
    public static By txtLocationNameInTowDestinationInMCDWindow;
    public static By lblEditComment;
    public static By btnCancelOnEditComment;
    public static By statusHiddenOrVisible;
    public static By btnSaveOnEditCommentScreen;
    public static By iconMinimizeOrMaximize;
    public static By lblStatusFromComments;
    public static By statusOfCommenet;
    public static By editLink;
    public static By lblFirstPacesetterValue;
    public static By lblSecondPacesetterValue;
    public static By drpDwnPacesetterCode1;
    public static By drpDwnPaceseterCode2;
    public static By btnSaveInService;
    public static By btnCancelInService;
    public static By btnPopOutInActionRequiredTab;
    public static By lnkSelectFirstRowInSearchResultsInBreakDownLoaciton;
    public static By lnkSelectFirstRowInSearchResultsInTowDestination;
    public static By lblEmptyResultsRowInSearchResultsInMCDWIndow;
    public static By lblCityInTowDestinationSearchResultsGridInServicesInMCD;
    public static By lblStateInTowDestinationSearchResultsGridInServicesInMCD;
    public static By lblZipInTowDestinationSearchResultsGridInServicesInMCD;
    public static By txtCommentsInEditLocationsAndTowDestinationsTabs;
    public static By btnGetAddressCoordinatesInMCDWindow;
    public static By resultsGridVerifications;
    static {
        //btnAsignCallinMCD = By.xpath("//*[@id='mcd-panel-content']/div[2]/div[2]/ul/li[7]/button/span[1]");
        btnAsignCallinMCD = By.xpath("//*[@id='mcd-panel-content']//span[@class='ui-button-text'][contains(text(),'AS')]");
        //selectFacility = By.cssSelector("div[class*='context-menu-group ALLOW_AS-'] div[title*='B/'] div");
        selectFacility = By.xpath("//*[contains(@class, 'context-menu-item')]//..//*[contains(@title, '/')]");
        selectFacilityZ = By.xpath("//*[contains(@class, 'context-menu-item')]//..//*[contains(@title, '*')]");
        selectFacilityB = By.xpath("//*[contains(@class, 'context-menu-item')]//..//*[contains(@title, '*')]");
        //lnkSelectFacility = By.cssSelector("div[class*='context-menu-group ALLOW_AS-'] div[title*='B/'] div");
        //btnDispatchUpdateinMCD = By.xpath("//*[@id='mcd-panel-content']/div[2]/div[2]/ul/li[8]/button");
        //btnDispatchUpdateinMCD = By.xpath("//*[@id='mcd-panel-content']/div[2]/div[2]/ul/li[6]/button");
        btnDispatchUpdateinMCD = By.xpath("//*[@id='mcd-panel-content']//span[@class='ui-button-text'][contains(text(),'DI')]");
        //btnEnrouteUpdateinMCD = By.xpath("//*[@id='mcd-panel-content']/div[2]/div[2]/ul/li[9]/button");
        btnEnrouteUpdateinMCD = By.xpath("//*[@id='mcd-panel-content']//span[@class='ui-button-text'][contains(text(),'ER')]");
        selEnrouteTimeinMCD = By.xpath("//*[@id='ALLOW_ER']/div[3]");
        //btnOnLocationUpdateinMCD = By.xpath("//*[@id='mcd-panel-content']/div[2]/div[2]/ul/li[10]/button");
        btnOnLocationUpdateinMCD = By.xpath("//*[@id='mcd-panel-content']//span[@class='ui-button-text'][contains(text(),'OL')]");
        //btnClearCallUpdateinMCD = By.xpath("//*[@id='mcd-panel-content']/div[2]/div[2]/ul/li[12]/button");
        btnClearCallUpdateinMCD = By.xpath("//*[@id=\"mcd-panel-content\"]//span[@class='ui-button-text'][contains(text(),'CL')]");
        selectPacesetterCodeJumpStart = By.xpath("//*[@id='res-code-table']/tbody/tr[1]/td");
        selectproblemResolutionCode = By.xpath("//*[@id='res-code-table']/tbody/tr[1]/td");
        continueButton = By.xpath("//*[contains(@class,'clearing-continue-btn')]");
        batteryTestedYes = By.id("battery-field-tested-yes");
        batteryFailedTestNo = By.id("battery-field-failed-no");
        odometerReading = By.id("battery-field-odometer");
        enterComments = By.id("battery-field-miscellaneous");
        submitButton = By.xpath("//*[contains(@class,'clearing-submit-btn')]");
        lblPaceSetterCodeInMCD = By.xpath("//div[@id='calldetails-tab-summary']//fieldset[@title='Trouble Summary']//div[1]/span");
        tabServiceInMCD = By.xpath("//a[contains(text(),'Service')]");
        btnWindowCloseInMCD = By.cssSelector("div[id='mcd-panel-btns'] [class='d3ui-panel-btn d3ui-panel-close-btn'][title='Close']");
        btnCloseCall = By.xpath("//span[contains(text(),'CL')]");
        selPaceSetterResolutionCode = By.xpath("//*[@id='res-code-table']/tbody/tr[1]/td");
        lblCallClearedStatus = By.xpath("//*[@id='mcd-call-status']/div[contains(text(),'CL - Cleared')]");
        txtReason=By.xpath("//*[@id='res-code-reason']");
        tabStatusUpdateInMCD = By.xpath("//*[contains(text(),'STATUS UPDATE')]");
        txtReasonOnStatusUpdate = By.xpath("//*[@id='dsu-reason']");
        btnUpdateOnStatusUpdate = By.xpath("//*[@id='status-update-btn-save']/span");
        btnETAinMCD = By.xpath("//button[@title='Set ETA']");
        selETATime = By.xpath("//div[@class='context-menu-group ALLOW_ETA']//span");
        linkMinimizeMCDwindow = By.xpath("//div[@id='mcd-panel-btns']/a[2]");
        txtStatusOfStatusUpdateInMCD = By.id("dsu-status");
        txtReasonOfStatusUpdateInMCD = By.id("dsu-reason");
        btnUpdateOfStatusUpdateTabInMCD = By.id("status-update-btn-save");
        selectFacilityOnAssignTabInMCD = By.xpath("//*[contains(@class, 'context-menu-item')]//..//*[contains(@title, '*')]");
        cancelinMCDClearCall = By.xpath("//*[@id='resolution-codes-tabs']//..//*[contains(text(),'Cancel')]");
        cancelCallServiceNotEnroute = By.xpath("//*[@id='res-code-table']//..//*[contains(text(),'Service Not En Route')]");
        selectSecondFacilityOnAssignTabInMCD = By.cssSelector("div[class*='context-menu-group ALLOW_AS-'] div:nth-child(3)");
        selectSecondFacilityOnDispatchTabInMCD = By.cssSelector("div[class*='context-menu-group ALLOW_DI-'] div:nth-child(3)");
        setTimeForETA = By.xpath("//div[@title='5 Min']");
        lblMemberFirstNameOnSummaryTabinMCD = By.xpath("//fieldset[@title='Member Summary']//span[@data-field='member.firstName']");
        lblMemberLastNameOnSummaryTabinMCD = By.xpath("//fieldset[@title='Member Summary']//span[@data-field='member.lastName']");
        lblMemberNumberOnSummaryTabinMCD = By.xpath("//fieldset[@title='Member Summary']//span[@data-field='member.memberNumber']");
        lblMemberAddressOnSummaryTabinMCD = By.xpath("//fieldset[@title='Member Summary']//span[@data-field='member.address.line1']");
        lblMemberCityOnSummaryTabinMCD = By.xpath("//fieldset[@title='Member Summary']//span[@data-field='member.address.city']");
        lblMemberStateOnSummaryTabinMCD = By.xpath("//fieldset[@title='Member Summary']//span[@data-field='member.address.state']");
        lblMemberZipOnSummaryTabinMCD = By.xpath("//fieldset[@title='Member Summary']//span[@data-field='member.address.zip']");
        lblBreakdownAddressLocationOnSummaryTabinMCD = By.xpath("//fieldset[@title='Breakdown Summary']//span[@data-field='breakdownLocation.address.line1']");
        lblVehicleYearOnSummaryTabinMCD = By.xpath("//*[contains(@data-groupkey,'SUMMARY-VEHICLE')]//span[@data-field='vehicle.year']");
        lblVehicleMakeOnSummaryTabinMCD = By.xpath("//*[contains(@data-groupkey,'SUMMARY-VEHICLE')]//span[@data-field='vehicle.make']");
        lblVehicleModelOnSummaryTabinMCD = By.xpath("//*[contains(@data-groupkey,'SUMMARY-VEHICLE')]//span[@data-field='vehicle.model']");
        lblVehicleColorOnSummaryTabinMCD = By.xpath("//*[contains(@data-groupkey,'SUMMARY-VEHICLE')]//span[@data-field='vehicle.color']");
        lblPaceSetterCodeOnSummaryTabinMCD = By.xpath("//fieldset[@title='Trouble Summary']//span[@data-field='pacesetter1']");
        lblTroubleCodeOnSummaryTabinMCD = By.xpath("//fieldset[@title='Trouble Summary']//span[@data-field='troubleCode1']");
        lblFunctionCodeOnSummaryTabinMCD = By.xpath("//*[contains(@data-groupkey,'FACILITY-SUMMARY')]//span[@data-field='facilityFunctionCode']");
        lblFacilityIdAndNameOnSummaryTabinMCD = By.xpath("//fieldset[@title='Facility Summary']//span/a[@data-field='facilityIdAndName']");
        btnTruckLoadOnSummaryTabinMCD = By.xpath("//*[contains(@data-groupkey,'FACILITY-SUMMARY')]//button[@title='Truck Load']");
        lnkMemberTabinMCD = By.xpath("//div[@id='call-details-tabs']//li[2]/a");
        lblMemberNumberOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.memberNumber']");
        lblMemberFirstNameOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.firstName']");
        lblMemberLastNameOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.lastName']");
        lblMemberAddressOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.address.line1']");
        lblMemberLevelOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.memberLevel']");
        lblMemberStatusOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.memberStatus']");
        lblMemberExpirationDateOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.memberExpiration']");
        lblMemberCallsUsedOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='dataFields.callsUsed.callProperty']");
        lblMemberCallsAllowedOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.callsAllowed']");
        lblLongTowAllowedOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.longTowAllowed']");
        lblMemberPhoneNumberOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-CONTACT-INFO')]//span[@title='Phone Number']");
        lnkServiceTabinMCD = By.xpath("//div[@id='call-details-tabs']//li[3]/a");
        lblPaceSetterCodeOnServiceTabinMCD = By.xpath("//*[contains(@data-groupkey,'SERVICE-PACESETTER')]//span[@data-field='pacesetter1']");
        lblTroubleCodeOnServiceTabinMCD = By.xpath("//*[contains(@data-groupkey,'SERVICE-PACESETTER')]//span[@data-field='troubleCode1']");
        lblServiceTypeInfoOnServiceTabinMCD = By.xpath("//*[contains(@data-groupkey,'SERVICE-SERVICE-TYPE')]//span[@data-field='troubleCode1']");
        lblFacilityNameAndNumberOnServiceTabinMCD = By.xpath("//*[contains(@data-groupkey,'SERVICE-SERVICING-FACILITY')]/div[2]/div[1]/span/a");
        btnShowBatteryServiceHistory = By.xpath("//fieldset[@data-groupkey='DI-SERVICE-ADDITIONAL-INFORMATION']/div[2]/button[@title='Show Battery Service History']");
        lnkLocationsTabinMCD = By.xpath("//div[@id='call-details-tabs']//li[4]/a");
        lblBreakDownLocationOnLocationsTabinMCD = By.xpath("//*[contains(@data-groupkey,'LOCATIONS-BREAKDOWN')]//span[@data-field='breakdownLocation.address.line1']");
        lblTowDestinationOnLocationsTabinMCD = By.xpath("//*[contains(@data-groupkey,'LOCATIONS-TOW-DESTINATION')]//span[@data-field='towDestination.address.line1']");
        lnkVehicleTabinMCD = By.xpath("//div[@id='call-details-tabs']//li[5]/a");
        lblVehicleTypeOnVehicleTabinMCD = By.xpath("//*[contains(@data-groupkey,'VEHICLE-VEHICLE')]//span[@data-field='vehicle.type']");
        lblVehicleYearOnVehicleTabinMCD = By.xpath("//*[contains(@data-groupkey,'VEHICLE-VEHICLE')]//span[@data-field='vehicle.year']");
        lblVehicleMakeOnVehicleTabinMCD = By.xpath("//*[contains(@data-groupkey,'VEHICLE-VEHICLE')]//span[@data-field='vehicle.make']");
        lblVehicleModelOnVehicleTabinMCD = By.xpath("//*[contains(@data-groupkey,'VEHICLE-VEHICLE')]//span[@data-field='vehicle.model']");
        lblVehicleColorOnVehicleTabinMCD = By.xpath("//*[contains(@data-groupkey,'VEHICLE-VEHICLE')]//span[@data-field='vehicle.color']");
        btnSPOnMCDWindow = By.xpath("//*[@id='mcd-panel-content']/div[2]/div[2]/ul/li[3]/button/span[1]");
        //btnTWOnMCDWindow = By.xpath("//*[@id='mcd-panel-content']/div[2]/div[2]/ul/li[11]/button/span");
        btnTWOnMCDWindow = By.xpath("//*[@id=\"mcd-panel-content\"]//span[@class='ui-button-text'][contains(text(),'TW')]");
        btnNOGOOnMCDWindow = By.xpath("//*[contains(text(),'No Go')]");
        btnNOServiceOnMCDWindow = By.xpath("//*[contains(text(),'No Service')]");

        btnOriginalTowDestinationOnMCDWindow = By.xpath("//*[contains(text(),'Original')]");
        txtAddressOnMCDWindow = By.xpath("//*[@id='sc-search-input']");
        iconSearchAddressOnMCDWindow = By.xpath("//*[@id='sc-search-button']");
        lnkClickOnFirstLink = By.xpath("//*[@id='sc-search-results']/tbody/tr[1]/td[3]/a/strong");
        txtCommentOnMCDWindow = By.id("sc-comment-textarea");
        lblCallSpottedStatus = By.xpath("//*[@id='mcd-call-status']/div[contains(text(),'SP - Spotted')]");
        lblCallAssignedStatus = By.xpath("//*[@id='mcd-call-status']/div[contains(text(),'AS - Assigned')]");
        lblCallDispatchedStatus = By.xpath("//*[@id='mcd-call-status']/div[contains(text(),'DI - Dispatched')]");
        lblCallENRouteStatus = By.xpath("//*[@id='mcd-call-status']/div[contains(text(),'ER - En Route')]");
        lblCallOnLocationStatus = By.xpath("//*[@id='mcd-call-status']/div[contains(text(),'OL - On Location')]");
        lblCallTowStatus = By.xpath("//*[@id='mcd-call-status']/div[contains(text(),'TW - Tow')]");
        txtFacilityInStautusUpdateWindow = By.id("dsu-facility");
        dropDownFacilityInStautusUpdateWindow = By.xpath("//*[@id='call-details-panel']/ul[3]/li/a");
        dropDownReasonInStautusUpdateWindow = By.xpath("//*[@id='call-details-panel']/ul[5]/li/a");
        lblLongTowUsedOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]/div[2]/div[13]/span");
        lblDOBOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.memberBirthday']");
        lblFunctionCodeOnServiceTabinMCD=By.xpath("//*[contains(@data-groupkey,'SERVICE-SERVICING-FACILITY')]//span[@data-field='facilityFunctionCode']");
        btnTruckLoadOnServiceTabinMCD=By.xpath("//*[contains(@data-groupkey,'SERVICE-SERVICING-FACILITY')]/div[2]/button");
        lblFacilityNameAndNumberOnServiceTabinDIMCD=By.xpath("//*[contains(@data-groupkey,'SERVICE-SERVICING-FACILITY')]/div[2]/div[2]/span/a");
        lblLanguagePreferenceOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-CONTACT-INFO')]//span[@data-field='languagePref']");
        lblETATimeOnMCDWindow=By.xpath("//*[@id='mcd-eta-div']/div[2]/span[@data-field='eta']");
        lblCommentsInMCDWindow = By.xpath("//div[@id='mcd-comments-table']//td[@class='comment-date-time-user-location-text']//span[@class='word-wrap']");
        lblMemberTypeOnMemberTabinMCD=By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.memberType']");
        txtMessageNoDataAvailableForOtherLocationInMCDWindow = By.xpath("//*[@id='sc-search-results']//*[contains(text(),'No data available in table')]");
        linkEnterAddreddManuallyForOttherLocationInMCDWindow = By.xpath("//*[@id='manual-entry-toggle']");
        txtEnterLocationForOtherLocationInMCDWindow=By.xpath("//*[@id='sc-manual-entry-wrapper']/div[2]/table/tbody/tr[1]/td/div/input");
        txtEnterCrossStreeet1ForOtherLocationInMCDWindow=By.xpath("//*[@id='sc-manual-entry-wrapper']/div[2]/table/tbody/tr[3]/td/div[1]/input");
        txtEnterCrossStreeet2ForOtherLocationInMCDWindow=By.xpath("//*[@id='sc-manual-entry-wrapper']/div[2]/table/tbody/tr[3]/td/div[2]/input");
        txtEnterCityForOtherLocationInMCDWindow=By.xpath("//*[@id='sc-manual-entry-wrapper']/div[2]/table/tbody/tr[4]/td/div/input");
        lblBatteryQuestionnaireInMCDWindow=By.xpath("//*[contains(text(),'Battery Questionnaire:')]");
        drpdwnStatusOnStatusUpdateTabInMCDWindow=By.xpath("//*[@id='dsu-status']/../button");
        drpdwnReasonOnStatusUpdateTabInMCDWindow=By.xpath("//*[@id='dsu-reason']/../button");
        txtTruckInStautusUpdateTab=By.id("dsu-truck");
        txtZoneInStautusUpdateTab=By.id("dsu-zone");
        txtTechInStautusUpdateTab=By.id("dsu-driver");
        txtETAInStautusUpdateTab=By.id("dsu-eta");
        txtDateInStautusUpdateTab=By.id("dsu-override-date");
        txtTimeInStautusUpdateTab=By.id("dsu-override-time");
        txtCommentsInStautusUpdateTab=By.id("dsu-comments");
        btnCancelOfStatusUpdateTabInMCD = By.id("status-update-btn-cancel");
        lblCallStatusOnMCDWindow = By.className("profile-call-status-descr");
        noTruckErrorText=By.xpath("//div[@class='message']/div");
        btnOKForNoTruckError=By.xpath("//*[contains(@aria-labelledby,'ui-dialog-title-error-dialog')]//button");
        drpdwnReasonGrayedOnStatusUpdateTabInMCDWindow=By.xpath("//*[@id='dsu-reason']/../button[@aria-disabled='true']");
        txtETAFieldAlert=By.xpath("//*[@id='status-update-form']/div[1]/div[1]/fieldset/span/div/div[1]");
        txtReasonGrayedout=By.xpath("//input[@id='dsu-reason'][@readonly='readonly']");
        btnPaymentOnMCDWindow=By.xpath("//*[@id='calldetails-garagepay-btn']/span[2]");
        drpDwnServicesAndChargesInMCDWindow =By.xpath("//*[@id='apd-plusService-label']");
        drpDwnServicesAndChargesValueOnMCDWindow =By.xpath("//ul[13]/li/a");
        btnSaveInServiceAndChargesInMCDWindow=By.xpath("//*[@id='apd-save-btn']");
        txtCostInServiceAndChargesInMCDWindow=By.xpath("//*[@id='apd-plusCharge']");
        txtCashCollectedInServiceAndChargesInMCDWindow=By.xpath("//*[@id='apd-cashCollected']");
        btnCloseInSericeAndChargesInMCDWindow=By.xpath("//*[@id='apd-cancel-btn']");
        errorMessageAtEnterReasonOnMCDWindow=By.xpath("//*[contains(@id,'ui-dialog-title-error-dialog')][contains(text(),'Errors')]");
        txtTroubleCodeDropdown=By.xpath("//input[@id='res-code-trouble-code']");
        txtPaceSetterCodeSummaryTab=By.xpath("(//*[contains(@data-fieldkey,'triagePacesetterCode1')]//span[@data-field='pacesetter1'])[1]");
        iconPaymentOnMCDWindow=By.id("calldetails-garagepay-btn");
        drpdwnServicesOnPaymentOfMCD=By.id("apd-plusService-label");
        txtCostAPD=By.id("apd-plusCharge");
        txtCashCollectedAPD=By.id("apd-cashCollected");
        btnAPDSave=By.id("apd-save-btn");
        btnCloseAPD=By.id("apd-cancel-btn");
        btnSubmitAPD=By.xpath("//div[contains(@class, 'clearing-submit-btn')]");
        lnkStatusHistory=By.id("mcd-call-status-history");
        lblStatusOnStatusHistoryTab=By.xpath("//table[@id='mcd-small-table']/tbody/tr//td[@title='CA - Cancelled']/../td[4]");
        lblReasonOnStatusHistoryTab=By.xpath("//table[@id='mcd-small-table']/tbody/tr//td[@title='CA - Cancelled']/../td[5]");
        lnkPlusIconForCommentsOnStatusHistoryTab=By.xpath("//table[@id='mcd-small-table']/tbody/tr//td[@title='CA - Cancelled']/../td[1]/a");
        lblPlusIconForCommentsSectionOnStatusHistoryTab=By.className("status-history-comment");
        lnkMaximizeMCDWindow=By.xpath("//*[@id='mcd-panel-btns']/a[1]");
        lnkMinimizeMCDWindow=By.xpath("//*[@id='mcd-pop-in-btn']");
        lblMemberLevelOnSummaryTab=By.xpath("//fieldset[@title='Member Summary']//span[@data-field='member.memberLevel']");
        txtCallTaker=By.className("d3-ui-icon-lock-text");
        //phoneNumberONMCD=By.xpath("//*[@id='calldetails-tab-summary']/div/div[1]/fieldset[1]/div[2]/div[13]/div[3]/div[2]/span");
        phoneNumberONMCD=By.xpath("//div[@id='calldetails-tab-member']/div/div[2]/fieldset[1]/div[2]/div[2]/div[2]/div[2]/span");
        btnHighlightedStatus=By.cssSelector("button[class*='current-status']");
        btnNextSelected=By.cssSelector("button[class*='next-logical-status']");
        editIconOnPencilIcon=By.xpath("(//span[contains(@class,'ui-button-text')][contains(text(),'Edit')])[2]");
        imgPencilIcon=By.xpath("(//span[contains(@class,'ui-button-text')][contains(text(),'Edit')])[1]");
        btnAdd=By.xpath("//span[contains(@class,'ui-button-text')][text()='Add']");
        txtAddComment=By.xpath("(//textarea[@id='add-comments-dialog-content'])[1]");
        btnSave=By.xpath("(//*[@id='ui-dialog-title-add-comments-dialog']//following::*[contains(text(),'Save')])[1]");
        commentedData=By.xpath("(//span[contains(@class,'word-wrap')])[2]");
        lblClearingTab=By.xpath("//*[@id='call-details-panel']/ul[1]/li[2]/a/span");
        btnPtaClose=By.id("pta-close");
        drpDwnAddSecondServicesAndChargesInMCDWindow=By.xpath("//*[@id='apd-addService-label']");
        btnBidCallInMCD = By.xpath("//*[@id='mcd-panel-content']//span[@class='ui-button-text'][contains(text(),'BD')]");
        btnBridgeCallinMCD = By.xpath("//*[@id='mcd-panel-content']//span[@class='ui-button-text'][contains(text(),'BD')]");
        btnDeclainCallinMCD = By.xpath("//*[@id='mcd-panel-content']//span[@class='ui-button-text'][contains(text(),'DC')]");
        btnPopOutInMCD = By.xpath("(//i[@class='icon-long-arrow-up'])[1]");
        lblClearCallStatusOnMCDHistoryWindow=By.cssSelector("div[id='status-history-call-icon'][class='d3ui-icon d3ui-icon-status d3ui-icon-status-CL status-icon-age-0']+div");
        lblReasonCodeOnMCDHisotryWindow=By.xpath("//table[@id='mcd-small-table']/tbody/tr//td[@title='CL - Cleared']/../td[5]");
        iconCloseOnStatusHistoryTabInMCDWindow=By.id("statushistory-x");
        lblPaceSetterValueInMCD = By.xpath("//span[contains(@data-field,'pacesetter1')]");
        txtTestCodeBattery=By.id("battery-field-test-code");
        batteryFailedTestYes = By.id("battery-field-failed-yes");
        batteryChargeYes = By.id("battery-field-charge-yes");
        txtBatteryType = By.id("battery-field-type");
        txtBatteryPrice = By.id("battery-field-price");
        batteryWarrantyYes=By.id("battery-field-warranty-yes");
        iconAddressverifiedOnOriginalTowDestinaton=By.className("address-verified-check d3ui-icon");
        lblCallBDStatus= By.xpath("//*[@id='mcd-call-status']/div[contains(text(),'BD - Bid')]");
        btnBDUpdateinMCD = By.xpath("//*[@id='mcd-panel-content']//span[@class='ui-button-text'][contains(text(),'BD')]");
        lblCallCAStatus= By.xpath("//*[@id='mcd-call-status']/div[contains(text(),'CA - Cancelled')]");
        lblTruckIDOnMCDSummaryScreen= By.cssSelector("fieldset[data-groupkey='P3-SUMMARY-FACILITY-SUMMARY'] div+div div:nth-child(3) span");
        btnAcknowledgeMCD=By.xpath("//button[contains(@class,'calldetails-update-ack-btn')]");
        btnDupeCallOnMCD=By.id("calldetails-update-duplicate-btn");
        txtDuplicateCallTab=By.xpath("//div[@id='call-details-panel']//span[contains(text(),'Duplicate This Call')]");
        lblCurrentCallOption= By.xpath("//h3[@id='duplicate-call-handler-tab-heading'][contains(text(),'Current Call')]");
         lblCallIDOnDuplicateCallTab=By.xpath("//table[@id='duplicate-call-current-call-table']//span[contains(text(),'Call ID')]");
        lblFacilityOnDuplicateCallTab=By.xpath("//table[@id='duplicate-call-current-call-table']//span[contains(text(),'Facility:')]");
        lblTruckOnDuplicateCallTab=By.xpath("//table[@id='duplicate-call-current-call-table']//span[contains(text(),'Truck')]");
        lblPaceSetterOnDuplicateCallTab=By.xpath("//table[@id='duplicate-call-current-call-table']//span[contains(text(),'Pacesetter Code')]");
        lblStatusOnDuplicateCallTab=By.xpath("//table[@id='duplicate-call-current-call-table']//span[contains(text(),'Status')]");
        lblNewDulicateCallInformationOnDuplicateCallTab=By.xpath("//h3[@id='duplicate-call-handler-tab-heading'][contains(text(),'New Duplicate Call Information')]");
        //lblNewDulicateCallInformationOnDuplicateCallTab=By.xpath("//h3[@id='duplicate-call-handler-tab-heading'][contains(text(),'New Duplicate Call Information')]");
        lblSpotToFacilityOnDuplicateCallTab=By.xpath("//div[@id='battery-service-result-radio']//label[contains(text(),'Spot to Facility')]");
        lblPaceSetterCodeDrpDwnOnDuplicateCallTab=By.xpath("//div[@id='battery-service-result-radio']//label[contains(text(),'Pacesetter Code')]");
        lblReasonDrpDwnOnDuplicateCallTab=By.xpath("//div[@id='battery-service-result-radio']//label[contains(text(),'Reason')]");
        lblCommentsDrpDwnOnDuplicateCallTab=By.xpath("//div[@id='battery-service-result-radio']//label[contains(text(),'Comments')]");
        btnDuplicateCallOnDuplicateCallTab=By.id("duplicate-call-handler-tab-duplicate-btn");
        errMsgForMandatoryFieldsOnDuplicateCallTab=By.xpath("//div[contains(@id,'error-dialog-')]//div[contains(text(),'not valid')]");
        btnErrorMsgOkOnDuplicateCallTab=By.xpath("//*[contains(@aria-labelledby,'ui-dialog-title-error-dialog')]//span[contains(text(),'OK')]");
        txtSpotFacility=By.id("duplicate-call-handler-tab-facility");
        txtPaceSetterCode=By.id("duplicate-call-handler-tab-pacesetter-code");
        txtReasonOnDuplicateCallTab=By.id("duplicate-call-handler-tab-reason");
        txtAreaForComments=By.id("duplicate-call-field-comment");
        MCDWindow = By.id("call-details-panel");
        lblMemberNeedsCallBack = By.xpath("//div[@title='NC Member Needs Callback Y']");
        iconPhone = By.xpath("//div[@class='d3ui-icon d3ui-icon-cm-2']");
        lnkEditAdditionalInfo=By.cssSelector("fieldset[data-groupkey*='SERVICE-ADDITIONAL-INFORMATION'] div a");
        txtSpecialEquipementInMCDServiceTab=By.id("mcd-specialEquipment-input");
        btnSpecialEquipementSaveButton=By.cssSelector("fieldset[data-groupkey*='SERVICE-ADDITIONAL-INFORMATION'] button[class='edit-special-equipment edit ui-button ui-widget ui-state-default ui-button-text-only ui-corner-left'] span");
        txtReasonCodeInUpdateStatus=By.id("csu-reason");
        txtCommentsInUpdateStatus=By.id("csu-comments");
        btnUpdatebuttonOnUpdateStatusPopup=By.cssSelector("div[id='callstatus-panel']+div div button:nth-child(1)");
        btnOkayOnErrorMessage=By.cssSelector("div[id*='error-dialog-']+div[class='ui-dialog-buttonpane ui-widget-content ui-helper-clearfix'] div button");
        lblSpecialEquipmentInMCDServiceTab=By.cssSelector("div[data-audit='serviceSpecialEquipment']");
        lblLatestCommentsInMCDWindow = By.xpath("//div[@id='mcd-comments-table']//td[@class='comment-date-time-user-location-text']//span[@class='word-wrap'][1]");
        sortdateInHisotrywindow=By.id("jqgh_mcd-small-table_date");
        lblStatusInHistoryStatus=By.xpath("//table[@id='mcd-small-table']/tbody/tr[2]/td[4]");
        btnDupeCallPopUpNameOnMCD=By.xpath("//button[@id='calldetails-update-duplicate-btn'][@class='calldetails-duplicate-btn ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only ui-state-hover']");
        lnkToSelectFacilityOnNewDuplicateCall=By.xpath("//div[@id='call-details-panel']//a[contains(text(),'N5102')]");
        lnkToSelectPacesetterCode=By.xpath("//div[@id='call-details-panel']//a[contains(text(),'L104')]");
        lnkSelectReasonOnNewDuplicateCall=By.xpath("//div[@id='call-details-panel']//a[contains(text(),'D2 - Failed OTG')]");
        lblCallIdOnMcdWindow=By.xpath("//span[@id='mcd-call-id-link']/span[2]");
        lblFacilityOnFacilitySummary=By.xpath("//div[@id='calldetails-tab-summary']//fieldset[@title='Facility Summary']//div[@title='Facility']/span");
        lnkToCloseTheOpendCallInMCD=By.xpath("//*[@id='mcd-call-loader-link']/i");
        lblStarColor=By.xpath("//*[@id='call-details-panel']//span/i[contains(@class,'mcd-favorite-btn-icon icon-star')]");
        btnShowBatteryServiceHistoryForRAP=By.xpath("//*[contains(@data-groupkey,'MEMBER-CONTACT-INFO')]//button[@title='Show Battery Service History']");
        btnShowDuplicateCallHistoryForRAP=By.xpath("//*[contains(@data-groupkey,'DI-SERVICE-DISPATCH-INFO')]//button[@title='Show Duplicate Call History']");
        lblvehiclevinOnServiceTabOfMCD=By.xpath("//*[contains(@data-groupkey,'SERVICE-RAP-INFO')]//span[@data-field='vehicle.vin']");
        lblvehicleOdometerOnServiceTabOfMCD=By.xpath("//*[contains(@data-groupkey,'SERVICE-RAP-INFO')]//span[@data-field='vehicle.odometer']");
        lblvehicleIsRAPCallOnServiceTabOfMCD=By.xpath("//*[contains(@data-groupkey,'SERVICE-RAP-INFO')]//span[@data-field='callFlags.rapCall']");
        lblvehicleRAPEDSCallNumberOnServiceTabOfMCD=By.xpath("//*[contains(@data-groupkey,'SERVICE-RAP-INFO')]//span[@data-field='rapCallDetails.edsCallNumber']");
        iconRAPCall=By.xpath("//div[@id='mcd-panel-content']//div[@class='call-status-icons-content']/div[2]");
        btnEditOnMCD=By.id("calldetails-edit-btn");
        btnPrintCallOnMCD=By.cssSelector("button[class='calldetails-print-btn ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only'] span:nth-child(1)");
        btnCrediCardOnMCD=By.id("calldetails-credit-card-btn");
        unDefinedError=By.cssSelector("div[id*='error-dialog-']+div[class='ui-dialog-buttonpane ui-widget-content ui-helper-clearfix'] div button");
        lblErrorMessageOnAlert=By.cssSelector("div[id*='error-dialog-'] div[class='message'] ");
        lblBatteryResoultionCodeOnClearingCall=By.xpath("//*[@id='res-code-table']/tbody/tr/td[contains(text(),'G306')]");

        lblDateAndCallIdInShowBatteryHistory = By.id("service-history-call-information-link");
        lblResoultionCodeLableInShowBatteryHistory = By.cssSelector("td[class='service-history-battery-information'] span:nth-child(1)");
        lblResoultionCodeValueInShowBatteryHistory = By.cssSelector("td[class='service-history-battery-information'] span:nth-child(2)");
        lblTestCodeLabelInShowBatteryHistory=By.cssSelector("td[class='service-history-battery-information'] span:nth-child(4)");
        lblTestCodeValueInShowBatteryHistory=By.cssSelector("td[class='service-history-battery-information'] span:nth-child(5)");
        lblFacilityLabelInShowBatteryHistory=By.cssSelector("td[class='service-history-battery-information'] span:nth-child(7)");
        lblFacilityValueInShowBatteryHistory=By.cssSelector("td[class='service-history-battery-information'] span:nth-child(8)");
        lblVehicleLableInShowBatteryHistory=By.cssSelector("td[class='service-history-battery-information'] span:nth-child(9)");
        lblVehicleValueInShowBatteryHisotry=By.cssSelector("td[class='service-history-battery-information'] span:nth-child(10)");
        iconCloseBatteryInformationTab=By.id("battery-information-tab-x");
        btnPrintInBatteryServiceHistory=By.id("printcall-print");
        lnkEditInMemberSummaryInMCDWindow=By.cssSelector("fieldset[data-groupkey='DI-SUMMARY-MEMBER-SUMMARY'] a[class='edit-member-number d3ui-tab-content-widget-header-edit-btn']");
        btnSaveForMemberSummaryInMCDWindow=By.cssSelector("fieldset[data-groupkey='DI-SUMMARY-MEMBER-SUMMARY'] button[class='edit-member-number-save ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only'] span");
        btnAddInMCDWindow=By.xpath("//div[@id='mcd-comments']//span[contains(text(),'Add')]");
        lnkCannedCommentsDroupDown= By.xpath("//div[@id='add-comments-dialog']//a[contains(text(),'Canned Comment')]");
        btnSaveCannedComments=By.xpath("(//div[@class='ui-dialog-buttonset']//span[contains(text(),'Save')])[2]");
        lblESTTimeInComments=By.xpath("//div[@id='mcd-comments-table']//td[@class='comment-date-time-user-location-text']//span[contains(text(),'EST')]");
        listCannedComments=By.xpath("//div[@class='auto-comments-list']/ul");
        txtUpdateStatus=By.id("csu-status");

        lblTowDestinationOnLocationsForRAPTabinMCD=By.xpath("//*[contains(@data-groupkey,'LOCATIONS-TOW-DESTINATION')]//span[@data-field='towDestination.address.crossStreet1']");
        lblMemberClubCodeOnMemberTabinMCD = By.xpath("//*[contains(@data-groupkey,'MEMBER-MEMBERSHIP')]//span[@data-field='member.clubCode']");
        lblCallDateInMCD=By.xpath("//span[@id='mcd-call-id-link']//span[@data-fieldkey='callDate']");
        selectFacilityOnAssignTabForDataUpdate = By.xpath("//*[contains(@class, 'context-menu-item')]//..//*[contains(@title, 'B/')]");
        listCannedComments=By.xpath("//div[@class='auto-comments-list']/ul/li");
        lblAddCommentsScreen=By.xpath("(//span[@id='ui-dialog-title-add-comments-dialog'][contains(text(),'Add ')])[1]");
        btnCancelOnAddComments=By.xpath("(//span[contains(@class,'ui-button-text')][text()='Cancel'])[9]");
        commentCountValueOnCommentSection=By.xpath("//div[@id='mcd-comments']//span[@class='ui-jqgrid-title']/span[2]");

        //locations Tab Tow Destination Edit and Locations Edits

        lnkEditTowDestinationInServicesTabInMCDWindow=By.cssSelector("fieldset[data-groupkey*='LOCATIONS-TOW-DESTINATION'] div a");
        lnkEditBreakDownLocationInServicesTabInMCDWindow = By.cssSelector("fieldset[data-groupkey*='LOCATIONS-BREAKDOWN'] div a");
        txtStreetNumberInServicesTabInMCDWindow=By.cssSelector("input[class*='block-number-input']");
        txtStreetNameInServicesTabInMCDWindow=By.cssSelector("input[class*='street-input']");
        txtCrossStreet1InServicesTabInMCDWindow=By.cssSelector("input[class*='cross-street-1-input']");
        txtCrossStreet2InServicesTabInMCDWindow=By.cssSelector("input[class*='cross-street-2-input']");
        txtCityInServicesTabInMCDWindow=By.cssSelector("input[class*='city-input']");
        txtStateInServicesTabInMCDWindow=By.cssSelector("input[class*='state-input']");
        txtZipInServicesTabInMCDWindow=By.cssSelector("input[class*='zip-input']");
        txtLandMarkInServicesTabInMCDWindow=By.cssSelector("input[class*='landmark']");
        txtLatitudeInServicesTabInMCDWindow=By.cssSelector("input[class*='latitude']");
        txtLongitudeInServicesTabInMCDWindow=By.cssSelector("input[class*='longitude']");
        lblAddressVerifiedInServicesTabInMCDWindow=By.cssSelector("div[class*='address-verified']");
        txtUpdateReasonInServicesTabInMCDWindow=By.cssSelector("input[class*='update-reason']");
        btnSaveButtonInServicesTabInMCDWindow=By.cssSelector("button[class*='save-button'] span");
        btnCancelButtonInServicesTabInMCDWindow=By.cssSelector("button[class*='cancel-button'] span");
        iconBreakDownLocationsCloseInMCDWindow=By.id("setBreakdownLocation-x");

        txtAddressSearchInServicesInMCDWindow=By.cssSelector("div[class*='d3ui-searchbox'] input[id*='search-input']");
        btnSearchButtonInServicesInMCDWindow=By.cssSelector("button[class*='d3ui-searchbox']");
        lnkManualAddressEntryInTowDestinationInMCDWindow=By.id("manual-entry-toggle");
        txtLocationNameInTowDestinationInMCDWindow=By.cssSelector("input[class*='location-name-input']");

        btnMemberHomeOnMCDWindow = By.xpath("//*[contains(text(),'Member Home')]");
        btnNoTowPerformedOnMCDWindow = By.xpath("//*[contains(text(),'No Tow Performed')]");
        btnRepairFacilityOnMCDWindow = By.xpath("//*[contains(text(),'Repair Facility')]");
        btnOtherLocationOnMCDWindow = By.xpath("//*[contains(text(),'Other Location')]");
        lblEditComment=By.id("ui-dialog-title-comments-edit");
        btnCancelOnEditComment=By.xpath("(//span[contains(@class,'ui-button-text')][text()='Cancel'])[6]");
        statusHiddenOrVisible=By.xpath("//div[@id='comments-edit']//select[@class='comment-status-select']");
        btnSaveOnEditCommentScreen=By.xpath("(//div[@class='ui-dialog-buttonset']//span[contains(text(),'Save')])[3]");
        iconMinimizeOrMaximize=By.xpath("//span[contains(@class,'ui-button-text')][text()='Minimize/Maximize']");
        lblStatusFromComments=By.xpath("//div[@id='mcd-comments-table']//tr[@key='20180216-20065']");
        editLink = By.xpath("(//a[contains(@class,'edit-trouble d3ui-tab-content-widget-header-edit-btn')])[2]");
        lblFirstPacesetterValue=By.xpath("(//span[contains(@data-field,'pacesetter1')][contains(text(),'L101 - Flat Tire w/spare')])[2]");
        lblSecondPacesetterValue=By.xpath("(//span[contains(@data-field,'troubleCode1')][contains(text(),'T1 - Flat Tire Service')])[2]");
        drpDwnPacesetterCode1=By.xpath("(//span[contains(@class,'ui-button-text')][text()='View Options'])[1]");
        drpDwnPaceseterCode2=By.xpath("(//span[contains(@class,'ui-button-text')][text()='View Options'])[2]");
        btnSaveInService=By.xpath("(//span[contains(@class,'ui-button-text')][text()='Save'])[2]");
        btnCancelInService=By.xpath("(//span[contains(@class,'ui-button-text')][text()='Cancel'])[2]");
        btnPopOutInActionRequiredTab=By.xpath("(//a[@class='d3ui-panel-btn popout-profile-btn'])");
        lnkSelectFirstRowInSearchResultsInBreakDownLoaciton=By.cssSelector("tr[class*='odd row-selected'] a");
        lblCityInTowDestinationSearchResultsGridInServicesInMCD=By.cssSelector("tr[class*='odd row-selected'] td:nth-child(3)");
        lblStateInTowDestinationSearchResultsGridInServicesInMCD=By.cssSelector("tr[class*='odd row-selected'] td:nth-child(4)");
        lblZipInTowDestinationSearchResultsGridInServicesInMCD=By.cssSelector("tr[class*='odd row-selected'] td:nth-child(5)");

        lnkSelectFirstRowInSearchResultsInTowDestination=By.cssSelector("tr[class*='odd row-selected'] td:nth-child(3)");
        lblEmptyResultsRowInSearchResultsInMCDWIndow=By.cssSelector("tr[class='odd row-selected'] td[class='dataTables_empty']");
        txtCommentsInEditLocationsAndTowDestinationsTabs=By.cssSelector("textarea[class*='update-comment-field']");
        btnGetAddressCoordinatesInMCDWindow=By.cssSelector("button[class*='verify-address ui-button'] span");
        resultsGridVerifications=By.id("DataTables_Table_0_wrapper");
    }

    public static By clickonStatusButton(String buttonName) {
        String cssValue = "button[class*='status-btn-" + buttonName + " ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-secondary']";
        dynamicstatusButton = By.cssSelector(cssValue);
        return dynamicstatusButton;
    }
    public static By phoneNumberValue(String phoneNum) {
        String xpath = "//div[@id='calldetails-tab-member']//span[contains(text(),'"+phoneNum+"')]";
        phNumber = By.xpath(xpath);
        return phNumber;
    }
    public static By btnCalldetailsUpdateActionButtons(String call) {
        String xpath = "//div[@id='calldetails-update-actions-btns']//span[contains(text(),'"+call+"')]";
        btnCalldetailsUpdateActionButtons = By.xpath(xpath);
        return btnCalldetailsUpdateActionButtons;
    }
    public static By selectCannedComment(String cannedComment){
        String xpath = "//div[@class='auto-comments-list']//a[contains(text(),'"+cannedComment+"')]";
        txtcannedComment = By.xpath(xpath);
        return txtcannedComment;
    }


    public static By selectOptionsActionsUPButton(String options){
        String xpath = "//span[contains(text(),'"+options+"')]/..";
        selectOptionsActionsUPButton = By.xpath(xpath);
        return selectOptionsActionsUPButton;
    }
    public static By hiddenCommentStatus(String CallId){
        String xpath = "//div[@id='mcd-comments-table']//tr[@key='"+CallId+"']";
        statusOfCommenet = By.xpath(xpath);
        return statusOfCommenet;
    }

}
